packages:
  - 'apps/*'
  - 'libs/*'
catalogs:
  prod:
    '@fastify/cookie': '^11.0.2'
    '@fastify/cors': '11.1.0'
    '@fastify/multipart': '9.3.0'
    '@fastify/static': '8.3.0'
    '@globalart/nestjs-logger': '1.0.11'
    '@globalart/nestjs-swagger': '1.2.6'
    '@globalart/oxide': '1.0.0'
    '@globalart/ddd': '1.1.0'
    '@grpc/grpc-js': '^1.14.0'
    '@grpc/reflection': '^1.0.4'
    '@keyv/redis': '^5.1.3'
    '@nestjs/axios': '^4.0.1'
    '@nestjs/cache-manager': '^3.0.1'
    '@nestjs/common': '^11.0.1'
    '@nestjs/config': '^4.0.2'
    '@nestjs/core': '^11.0.1'
    '@nestjs/graphql': '13.2.0'
    '@nestjs/microservices': '11.1.8'
    '@nestjs/platform-express': '^11.0.1'
    '@nestjs/platform-fastify': '11.1.8'
    '@nestjs/swagger': '11.2.1'
    '@nestjs/terminus': '^11.0.0'
    '@nestjs/typeorm': '^11.0.0'
    'axios': '1.13.1'
    'bcrypt': '^6.0.0'
    'cache-manager': '7.2.4'
    'class-validator': '^0.14.2'
    'deepmerge': '^4.3.1'
    'express': '^5.1.0'
    'fastify': '5.6.1'
    'generate-password': '^1.7.1'
    'jsonwebtoken': '^9.0.2'
    'kafkajs': '^2.2.4'
    'keyv': '^5.5.3'
    'lodash': '^4.17.21'
    'moment': '^2.30.1'
    'nestjs-cls': '^6.0.1'
    'nestjs-zod': '5.0.1'
    'reflect-metadata': '^0.2.2'
    'request-ip': '^3.3.0'
    'rxjs': '^7.8.1'
    'typeorm': '0.3.27'
    'typeorm-naming-strategies': '^4.1.0'
    'typeorm-transactional': '^0.5.0'
    'uuid': '13.0.0'
    'zod': '4.1.12'
    'zod-openapi': '5.4.3'
  dev:
    '@eslint/eslintrc': '^3.2.0'
    '@eslint/js': '^9.18.0'
    '@nestjs/cli': '^11.0.0'
    '@nestjs/schematics': '^11.0.0'
    '@nestjs/testing': '^11.0.1'
    '@swc/cli': '^0.7.8'
    '@swc/core': '1.14.0'
    '@types/express': '^5.0.0'
    '@types/jest': '^30.0.0'
    '@types/node': '^22.10.7'
    '@types/request-ip': '^0.0.41'
    'eslint': '^9.18.0'
    'eslint-config-prettier': '^10.0.1'
    'eslint-plugin-prettier': '^5.2.2'
    'globals': '^16.0.0'
    'jest': '^30.0.0'
    'npm-run-all2': '^8.0.4'
    'prettier': '^3.4.2'
    'rimraf': '6.1.0'
    'source-map-support': '^0.5.21'
    'ts-node': '^10.9.2'
    'tsconfig-paths': '^4.2.0'
    'tsdown': '0.15.12'
    'turbo': '^2.4.2'
    'typescript': '^5.7.3'
    'typescript-eslint': '^8.20.0'